name: 安徽组播

on:
  schedule:
    - cron: '0 6,18,23 * * *'
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
        
      - name: Install Dependencies
        run: |
          pip install bs4 requests playwright datetime
          sudo apt-get update
          sudo apt-get install -y yt-dlp sed nmap     
      # - name: 检测组播源
      #   run: |
      #     cd $GITHUB_WORKSPACE
      #     bash py/安徽组播/zubo.sh
      #     cat py/安徽组播/txt/安徽电信.txt
          
      - name: Run anhui_zubo.py
        run: python ${{ github.workspace }}/py/安徽组播/anhui_zubo.py
        
      - name: 提交更改
        run: |
          git config --local user.email "2856364053@qq.com"
          git config --local user.name "adminouyang"
          git add .
          git commit -m "安徽组播更新: `date`"
          #git commit *.m3u -m "action: `date`"
          git push -f
          #git pull --rebase
          git push -f
