name: 优质源

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest
    env:
     TZ: Asia/Shanghai

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      - name: Run main.py
        run: python ${{ github.workspace }}/py/优质源/main.py
     
        
      - name: 提交更改
        run: |

          git config --local user.email "2856364053@qq.com"
          git config --local user.name "adminouyang" 
          git add .
          git commit -m "action: `date`"
          #git commit -m "action: `date`"
          git push -f
          #git pull --rebase

